### ISSUE TITLE
Can't start robot server

### ISSUE THREAD

**Issue by mphamhung** [jr-robotics/robo-gym#20]
Using docker with melodic+python3.7

`2021-03-23 23:02:17,679 - serverManager - ERROR - Failed to add Robot Server
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/robo_gym_server_modules/server_manager/server.py", line 118, in StartNewServer
    rl_server = self.srv_mngr.add_rl_server(cmd= request.cmd, gui= request.gui)
  File "/home/user/.local/lib/python2.7/site-packages/robo_gym_server_modules/server_manager/server.py", line 71, in add_rl_server
    session = self.new_session(name = repr(grpc_port))
  File "/home/user/.local/lib/python2.7/site-packages/robo_gym_server_modules/server_manager/server.py", line 39, in new_session
    return self.tmux_srv.new_session(session_name = name, kill_session = True, attach = False)
  File "/home/user/.local/lib/python2.7/site-packages/libtmux/server.py", line 570, in new_session
    session = Session(server=self, **session)
  File "/home/user/.local/lib/python2.7/site-packages/libtmux/session.py", line 61, in __init__
    raise ValueError('Session requires a `session_id`')
ValueError: Session requires a `session_id`
`

**Comment by mphamhung** [comment]
Duplicate of #18
