### ISSUE TITLE
Stable-Baselines ERROR

### ISSUE THREAD

**Issue by lgortiz1** [jr-robotics/robo-gym#79]
hello community, I am trying to perform the UR3 training about end-effector positioning with the use of Stable-Baselines.

I am using Ubuntu 20.04
ROS noetic
python 3.8
Stable-Baselines3 = 2.0.0.0
tf = 2 

I have seen in the Stable-Baselines example that it uses the previous version, but when using python 3.8 it is not possible to install TF=1.15 for Stable-Baselines.
So I chose to use Stable-Baselines3, when I run the code for the MiR100 robot it works fine.

The problem is when I change the environment to UR3 "EndEffectorPositioningURSim-v0", the simulation runs in gazebo fine, but when I run the line "model.learn(total_timesteps=15000)" it generates the following error

can anyone help me how can I fix the error, or any recommendation of versions in which stable baseline works well.
I have thought about moving everything to ubuntu 18.04, but the idea is to keep developing some new not to go backwards.

Starting new Robot Server | Tentative 1 of 10
Successfully started Robot Server at 127.0.0.1:50551
/home/luigi/.local/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:174: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:195: UserWarning: WARN: The result returned by `env.reset()` was not a tuple of the form `(obs, info)`, where `obs` is a observation and `info` is a dictionary containing additional information. Actual type: `<class 'numpy.ndarray'>`
  logger.warn(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:219: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
  logger.deprecation(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:225: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(done, (bool, np.bool8)):
^CTraceback (most recent call last):
  File "/home/luigi/robogym_ws/src/robo-gym/docs/examples/random_agent_sim.py", line 18, in <module>
    state, reward, done, info = env.step(env.action_space.sample())
  File "/home/luigi/robogym_ws/src/robo-gym/robo_gym/wrappers/exception_handling.py", line 9, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/luigi/.local/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)
  File "/home/luigi/.local/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 39, in step
    return self.env.step(action)
  File "/home/luigi/robogym_ws/src/robo-gym/robo_gym/envs/ur/ur_ee_positioning.py", line 264, in step
    state, reward, done, info = super().step(action)
  File "/home/luigi/robogym_ws/src/robo-gym/robo_gym/envs/ur/ur_base_env.py", line 197, in step
    rs_state = self.client.send_action_get_state(rs_action.tolist()).state_dict
  File "/home/luigi/.local/lib/python3.8/site-packages/robo_gym_server_modules/robot_server/client.py", line 40, in send_action_get_state
    msg = self.robot_server_stub.SendActionGetState(robot_server_pb2.Action(action = action), timeout = 20 )
  File "/home/luigi/.local/lib/python3.8/site-packages/grpc/_channel.py", line 1157, in __call__
    ) = self._blocking(
  File "/home/luigi/.local/lib/python3.8/site-packages/grpc/_channel.py", line 1141, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 189, in grpc._cython.cygrpc._next_call_event
  File "/usr/lib/python3.8/threading.py", line 246, in __enter__
    def __enter__(self):
KeyboardInterrupt
^C
luigi@luigi:~/robogym_ws/src/robo-gym/docs/examples$ ^C
luigi@luigi:~/robogym_ws/src/robo-gym/docs/examples$ /bin/python3 /home/luigi/robogym_ws/src/robo-gym/docs/examples/stable-baselines/td3_script.py
2024-01-25 19:29:25.298682: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-25 19:29:25.376278: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-25 19:29:26.503590: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Starting new Robot Server | Tentative 1 of 10
Successfully started Robot Server at 127.0.0.1:49103
/home/luigi/.local/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:174: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:195: UserWarning: WARN: The result returned by `env.reset()` was not a tuple of the form `(obs, info)`, where `obs` is a observation and `info` is a dictionary containing additional information. Actual type: `<class 'numpy.ndarray'>`
  logger.warn(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:219: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
  logger.deprecation(
/home/luigi/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:225: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(done, (bool, np.bool8)):
Traceback (most recent call last):
  File "/home/luigi/robogym_ws/src/robo-gym/docs/examples/stable-baselines/td3_script.py", line 19, in <module>
    model.learn(total_timesteps=15000)
  File "/home/luigi/.local/lib/python3.8/site-packages/stable_baselines3/td3/td3.py", line 195, in learn
    return super(TD3, self).learn(
  File "/home/luigi/.local/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 266, in learn
    rollout = self.collect_rollouts(
  File "/home/luigi/.local/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 472, in collect_rollouts
    new_obs, reward, done, infos = env.step(action)
  File "/home/luigi/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/home/luigi/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 51, in step_wait
    return (self._obs_from_buf(), np.copy(self.buf_rews), np.copy(self.buf_dones), deepcopy(self.buf_infos))
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'google.protobuf.pyext._message.ScalarMapContainer' object

![Captura de pantalla de 2024-01-25 19-43-48](https://github.com/jr-robotics/robo-gym/assets/155060924/c60a9289-4abd-47d5-8538-f135f6da7b40)

**Comment by f4rh4ng** [comment]
Hi,
Check out the following issue in the forum. It will most likely help solving your problem. 🙂 

https://github.com/jr-robotics/robo-gym/issues/58
